// Generated by ReScript, PLEASE EDIT WITH CARE


function boolOrAlways(value) {
  if (typeof value === "object") {
    return value.VAL;
  } else {
    return "always";
  }
}

var refetchOnWindowFocus = boolOrAlways;

export {
  boolOrAlways ,
  refetchOnWindowFocus ,
}
/* No side effect */
