// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function useCancelSelection(callback) {
  var handleDeletePress = function ($$event) {
    if ($$event.key === "Escape") {
      return Curry._1(callback, undefined);
    }
    
  };
  React.useEffect((function () {
          document.addEventListener("keydown", handleDeletePress);
          return (function (param) {
                    document.removeEventListener("keydown", handleDeletePress);
                  });
        }), []);
}

export {
  useCancelSelection ,
}
/* react Not a pure module */
