// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Decco from "decco/src/Decco.bs.mjs";
import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as QueryClient from "../bindings/react-query/QueryClient.bs.mjs";
import * as ReactQuery from "react-query";
import * as ReactQuery_Utils from "../bindings/react-query/ReactQuery_Utils.bs.mjs";

var queryKey = "countries";

var apiUrl = "https://gist.githubusercontent.com/rusty-key/659db3f4566df459bd59c8a53dc9f71f/raw/4127f9550ef063121c564025f6d27dceeb279623/counties.json";

function country_encode(v) {
  return Js_dict.fromArray([
              [
                "label",
                Decco.stringToJson(v.label)
              ],
              [
                "value",
                Decco.stringToJson(v.value)
              ]
            ]);
}

function country_decode(v) {
  var dict = Js_json.classify(v);
  if (typeof dict === "number") {
    return Decco.error(undefined, "Not an object", v);
  }
  if (dict.TAG !== /* JSONObject */2) {
    return Decco.error(undefined, "Not an object", v);
  }
  var dict$1 = dict._0;
  var label = Decco.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(dict$1, "label"), null));
  if (label.TAG === /* Ok */0) {
    var value = Decco.stringFromJson(Belt_Option.getWithDefault(Js_dict.get(dict$1, "value"), null));
    if (value.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: {
                label: label._0,
                value: value._0
              }
            };
    }
    var e = value._0;
    return {
            TAG: /* Error */1,
            _0: {
              path: ".value" + e.path,
              message: e.message,
              value: e.value
            }
          };
  }
  var e$1 = label._0;
  return {
          TAG: /* Error */1,
          _0: {
            path: ".label" + e$1.path,
            message: e$1.message,
            value: e$1.value
          }
        };
}

function countries_encode(v) {
  return Decco.arrayToJson(country_encode, v);
}

function countries_decode(v) {
  return Decco.arrayFromJson(country_decode, v);
}

function useQuery(prim) {
  return ReactQuery.useQuery(prim);
}

function queryOptions(prim0, prim1, prim2, prim3) {
  var tmp = {};
  if (prim0 !== undefined) {
    tmp.queryKey = Caml_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.queryFn = Caml_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp.refetchOnWindowFocus = Caml_option.valFromOption(prim2);
  }
  return tmp;
}

function handleFetch(signal) {
  return QueryClient.get(Caml_option.some(signal), "" + apiUrl + "").then(countries_decode);
}

var initialState_countries = [];

var initialState = {
  isLoading: false,
  error: "",
  countries: initialState_countries
};

function reducer(state, action) {
  if (typeof action === "number") {
    return {
            isLoading: true,
            error: "",
            countries: state.countries
          };
  } else if (action.TAG === /* Error */0) {
    return {
            isLoading: false,
            error: action._0,
            countries: state.countries
          };
  } else {
    return {
            isLoading: false,
            error: "",
            countries: action._0
          };
  }
}

function useCountries(param) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  var controller = new AbortController();
  var signal = controller.signal;
  var fetchResult = ReactQuery.useQuery(queryOptions(queryKey, (function (param) {
              return handleFetch(signal);
            }), Caml_option.some(ReactQuery_Utils.refetchOnWindowFocus({
                    NAME: "bool",
                    VAL: false
                  })), undefined));
  React.useEffect((function () {
          if (fetchResult.isLoading) {
            Curry._1(dispatch, /* Loading */0);
          } else if (fetchResult.isError) {
            Curry._1(dispatch, {
                  TAG: /* Error */0,
                  _0: "Error while fetching countries from server"
                });
          } else {
            var match = fetchResult.data;
            if (match !== undefined) {
              if (match.TAG === /* Ok */0) {
                Curry._1(dispatch, {
                      TAG: /* SuccessCountries */1,
                      _0: match._0
                    });
              } else {
                Curry._1(dispatch, {
                      TAG: /* SuccessCountries */1,
                      _0: []
                    });
              }
            } else {
              Curry._1(dispatch, {
                    TAG: /* SuccessCountries */1,
                    _0: []
                  });
            }
          }
        }), [fetchResult.isLoading]);
  return [
          state.isLoading,
          state.error,
          state.countries,
          signal
        ];
}

export {
  queryKey ,
  apiUrl ,
  country_encode ,
  country_decode ,
  countries_encode ,
  countries_decode ,
  useQuery ,
  queryOptions ,
  handleFetch ,
  initialState ,
  reducer ,
  useCountries ,
}
/* react Not a pure module */
