// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jzon from "rescript-jzon/src/Jzon.bs.mjs";

var country = Jzon.object2((function (param) {
        return [
                param.label,
                param.value
              ];
      }), (function (param) {
        return {
                TAG: /* Ok */0,
                _0: {
                  label: param[0],
                  value: param[1]
                }
              };
      }), Jzon.field("label", Jzon.string), Jzon.field("value", Jzon.string));

var countries = Jzon.array(country);

var Codecs = {
  country: country,
  countries: countries
};

export {
  Codecs ,
}
/* country Not a pure module */
