// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var QueryClientError = /* @__PURE__ */Caml_exceptions.create("QueryClient.QueryClientError");

function validateRequestError(response) {
  if (response.ok) {
    return Promise.resolve(response);
  } else {
    return Promise.reject({
                RE_EXN_ID: QueryClientError,
                _1: response
              });
  }
}

function get(url) {
  return fetch("" + url + "", {
                  method: "GET"
                }).then(validateRequestError).then(function (response) {
              return response.json();
            });
}

export {
  QueryClientError ,
  validateRequestError ,
  get ,
}
/* No side effect */
