// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactSelect from "react-select";
import * as JsxRuntime from "react/jsx-runtime";

var optionComponent = ReactSelect.components.Option;

function make(props) {
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(React.createElement(optionComponent, props))
            });
}

var ReactSelectOption = {
  optionComponent: optionComponent,
  make: make
};

var menuListComponent = ReactSelect.components.MenuList;

function make$1(props) {
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(React.createElement(menuListComponent, props))
            });
}

var ReactSelectMenuList = {
  menuListComponent: menuListComponent,
  make: make$1
};

export {
  ReactSelectOption ,
  ReactSelectMenuList ,
}
/* optionComponent Not a pure module */
