// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as FlagIcon from "./FlagIcon.bs.mjs";
import * as TriangleNeutral from "./TriangleNeutral.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  var onClick = props.onClick;
  var value = props.value;
  var className = props.className;
  var classList = className !== undefined ? "" + className + "" : "";
  return JsxRuntime.jsxs("button", {
              children: [
                value !== undefined ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
                        children: [
                          JsxRuntime.jsx(FlagIcon.make, {
                                country: value.value
                              }),
                          value.label
                        ]
                      }) : JsxRuntime.jsx(JsxRuntime.Fragment, {}),
                JsxRuntime.jsx(TriangleNeutral.make, {})
              ],
              className: classList,
              type: "button",
              onClick: (function (param) {
                  Curry._1(onClick, undefined);
                })
            });
}

var make = Button;

export {
  make ,
}
/* FlagIcon Not a pure module */
