// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as FlagIcon from "./FlagIcon.bs.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as TriangleNeutralIcon from "./TriangleNeutralIcon.bs.mjs";

var fallbackButtonProps = {
  label: "No selected Country",
  value: "xx"
};

function Button(props) {
  var onClick = props.onClick;
  var value = props.value;
  var className = props.className;
  var classList = className !== undefined ? "" + className + "" : "";
  var buttonData = value !== undefined ? value : fallbackButtonProps;
  return JsxRuntime.jsxs("button", {
              children: [
                JsxRuntime.jsxs(JsxRuntime.Fragment, {
                      children: [
                        JsxRuntime.jsx(FlagIcon.make, {
                              country: buttonData.value
                            }),
                        buttonData.label
                      ]
                    }),
                JsxRuntime.jsx(TriangleNeutralIcon.make, {})
              ],
              ref: Caml_option.some(props.buttonRef),
              className: classList,
              autoFocus: props.autoFocus,
              type: "button",
              onClick: (function (param) {
                  Curry._1(onClick, undefined);
                })
            });
}

var make = Button;

export {
  fallbackButtonProps ,
  make ,
}
/* FlagIcon Not a pure module */
