// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Button from "./Button.bs.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import MagnifierSvg from "../assets/magnifier.svg";

var magnifierLogo = MagnifierSvg;

var options = [
  {
    value: "chocolate",
    label: "Chocolate"
  },
  {
    value: "strawberry",
    label: "Strawberry"
  },
  {
    value: "vanilla",
    label: "Vanilla"
  }
];

function CountrySelect(props) {
  var onChange = props.onChange;
  var country = props.country;
  var handleCountryChange = function (e) {
    var newCountry = e.target.value;
    Curry._1(onChange, newCountry);
    console.log(" ~ file: CountrySelect.res:18 ~ handleCountryChange ~ newCountry:\", " + newCountry + "");
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Button.make, {
                      children: Caml_option.some("" + country + "")
                    }),
                JsxRuntime.jsxs("select", {
                      children: [
                        JsxRuntime.jsx("option", {
                              children: "Search",
                              hidden: true,
                              disabled: true,
                              value: "search"
                            }),
                        Belt_Array.mapWithIndex(options, (function (i, option) {
                                return JsxRuntime.jsx("option", {
                                            children: "" + option.label + "",
                                            value: option.value
                                          }, "" + option.value + "-" + String(i) + "");
                              }))
                      ],
                      value: country,
                      onChange: handleCountryChange
                    })
              ],
              className: props.className
            });
}

var make = CountrySelect;

export {
  magnifierLogo ,
  options ,
  make ,
}
/* magnifierLogo Not a pure module */
