// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import FlagIconModuleCss from "./FlagIcon.module.css";

import '../../node_modules/flag-icon-css/css/flag-icons.min.css'
;

var styles = FlagIconModuleCss;

function FlagIcon(props) {
  return JsxRuntime.jsx("span", {
              className: "flag-icon flag-icon-" + props.country + " " + styles.flagIcon + ""
            });
}

var make = FlagIcon;

export {
  styles ,
  make ,
}
/*  Not a pure module */
