// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function MagnifierIcon(props) {
  return JsxRuntime.jsx("svg", {
              children: JsxRuntime.jsx("path", {
                    clipRule: "evenodd",
                    d: "M6 11c1.02 0 1.967-.305 2.758-.829l3.302 3.299 1.41-1.41-3.299-3.302A5 5 0 106 11zm3.2-5a3.2 3.2 0 11-6.4 0 3.2 3.2 0 016.4 0z",
                    fill: "#333",
                    fillRule: "evenodd"
                  }),
              className: props.className,
              height: "14",
              width: "14",
              fill: "none",
              viewBox: "0 0 14 14",
              xmlns: "http://www.w3.org/2000/svg"
            });
}

var make = MagnifierIcon;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
