// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as FlagIcon from "./FlagIcon.bs.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactSelect from "../bindings/react-select/ReactSelect.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function make(props) {
  var children = Caml_option.some(JsxRuntime.jsxs(JsxRuntime.Fragment, {
            children: [
              JsxRuntime.jsx(FlagIcon.make, {
                    country: props.value
                  }),
              JsxRuntime.jsx("span", {
                    children: props.label,
                    className: "overflow-hidden text-ellipsis whitespace-nowrap ml-2"
                  })
            ]
          }));
  var newrecord = Caml_obj.obj_dup(props);
  return JsxRuntime.jsx(ReactSelect.ReactSelectOption.make, (newrecord.children = Caml_option.some(children), newrecord));
}

export {
  make ,
}
/* FlagIcon Not a pure module */
