// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function TriangleNeutral(props) {
  return JsxRuntime.jsx("svg", {
              children: JsxRuntime.jsx("path", {
                    clipRule: "evenodd",
                    d: "M0 2h8L4 7 0 2z",
                    fill: "#333",
                    fillRule: "evenodd"
                  }),
              height: "8",
              width: "8",
              fill: "none",
              viewBox: "0 0 8 8",
              xmlns: "http://www.w3.org/2000/svg"
            });
}

var make = TriangleNeutral;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
