// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactSelect from "../bindings/react-select/ReactSelect.bs.mjs";
import * as MagnifierIcon from "./MagnifierIcon.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import ValueContainerModuleCss from "./ValueContainer.module.css";

var styles = ValueContainerModuleCss;

function make(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(MagnifierIcon.make, {
                      className: styles.magnifierIcon
                    }),
                ReactSelect.ReactSelectValueContainer.make(props)
              ],
              className: styles["value-container-wrapper"]
            });
}

export {
  styles ,
  make ,
}
/* styles Not a pure module */
