// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CountrySelect from "./component/CountrySelect.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return "United States";
      });
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(CountrySelect.make, {
                    country: match[0],
                    className: "w-[230px]"
                  }),
              className: "h-screen-dvh w-screen-dvh flex justify-center pt-32"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
